[Feature] BottomSheetViewController 구현
YAPP-Github/21st-iOS-Team-2-iOS pull request #10
Opened 2023-01-04 06:41 UTC by leeari95

### 📕 Issue

> 관련 이슈를 연결합니다.

fix x

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역, 변경 사항을 포함합니다.

- [x] BottomSheetViewController 구현
- [ ] 실행 테스트용으로 메인피드 화면에 BottomSheet를 띄우는 로직 구현

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

### 📱 테스트 방법

> PR 리뷰어가 변경사항을 확인할 수 있는 방법을 서술합니다. 의도하는 테스트 결과도 같이 서술하면 더 좋습니다.

- 앱 실행 후 메인피드 화면에서 상단 주소부분을 탭하면 Bottom Sheet가 열립니다.
- BottomSheet 내부에 ModalStyle에 따라 뷰를 띄우는 높이를 설정할 수 있어요.

### 📝 리뷰 노트

> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있다면 PR 리뷰를 돕기 위해 서술합니다. 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트를 요청하는 경우에도 같이 작성해주면 좋습니다.

- 삽질해가면서 만든 뷰라서 미흡한 점이 많을 것 같아요. 잘 부탁드립니다. 🙏🏻
- Bottom Sheet 안에 ContentView를 넣어 띄우는 방식이 괜찮은지 봐주세요.
	- 혹시 다른 좋은 방법이 있다면 적극적으로 의견주세요!

### 🏞️ 스크린샷

> 작업 내용과 관련된 화면을 추가합니다.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/75905803/210497591-6709286b-5743-4bc2-976b-8ee2cb866a9a.png">

2023-01-04 06:49 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +        coordinator: MainCoordinatorInterface
아.. 여기서는 코디네이터가 필요 없겠네요. 수정하겠습니다!

2023-01-06 11:43 UTC, dudtjs1021ej requested changes
아리 커스텀 바텀시트 구현해주셔서 감사합니다! 4가지 타입 모두 잘 동작하는 것 확인했습니다😆
덕분에 앞으로 UI 구현하는데 더 편해지겠네요👍
아래 간단한 코멘트 남겨놨으니 확인해주시구 답장 부탁드립니다!

2023-01-06 11:43 UTC, dudtjs1021ej commented on Fitfty/Projects/Coordinator/Sources/MainCoordinator.swift
> +        test.navigationItem.title = "주소를 변경해볼까요?"
[질문] 주소 화면은 계층적인 구조가 아니라 modal로 화면 전환을 해도 될 것 같은데 NavigationController를 사용하신 이유가 궁금합니다!

2023-01-06 11:43 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +        view.addSubviews(contentViewController.view)
`view.addSubviews(contentViewController.view)`
[p4] 이 부분은 setUpLayout()에 들어가는 게 더 맞을 것 같네요!

2023-01-06 11:43 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +    @objc func viewPanned(_ panGestureRecognizer: UIPanGestureRecognizer) {
[p4] 메소드 이름을 동사로 시작해서 `pannedView`는 어떠신가요?

2023-01-06 11:43 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +        view.addGestureRecognizer(dimmedTap)
```suggestion
        backgroundView.addGestureRecognizer(dimmedTap)
```

[p3] 현재 bottomSheet를 눌러도 바로 dismiss되게 동작하는데 
이보단 뒤에 backgroundView 탭할 시에만 dismiss되는 동작이 더 맞는 것 같습니다😁

2023-01-07 01:45 UTC, leeari95 commented on Fitfty/Projects/Coordinator/Sources/MainCoordinator.swift
> +        test.navigationItem.title = "주소를 변경해볼까요?"
이 부분은 뷰컨트롤러를 생성하는 코드입니다! 실제로 화면을 띄워주는건 modal로 띄우고 있어요!
네비게이션 컨트롤러를 사용한 이유는, 단순히 네비게이션 바를 활용하기 위해서 사용하게 되었어요.
저도 궁금한게... 현재 코디네이터를 새로 만들지 않고 그냥 모달로 띄우고 있는데, 이게 맞는건지 모르겠어요...
모달이 띄워졌으면 새로운 플로우니까 따로 코디네이터를 만들어서 화면을 띄워야 할까요?

2023-01-07 01:47 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +        view.addSubviews(contentViewController.view)
setUpLayout()에 들어가는게 맞다는 것이 어떤 이유에서 말씀해주신 걸까요?
`bottomSheetView` 내부에 addSubview를 하는 작업이라서, 인스턴스 생성하는 곳에 두었습니다!

2023-01-07 03:32 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +        view.addSubviews(contentViewController.view)
전 addSubview 메소드 자체가 layout관련된 코드라고 생각했습니다!
아리 말을 들어보니 인스턴스 생성할 때 처리해도 될 것 같네요😄

2023-01-07 04:50 UTC, dudtjs1021ej commented on Fitfty/Projects/Coordinator/Sources/MainCoordinator.swift
> +        test.navigationItem.title = "주소를 변경해볼까요?"
아아 이해했습니다!
음.. 바텀시트를 띄우는 동작을 MainCoordinator에서 처리하니 상관 없을 것 같기도한데 이 부분은 저도 코디네이터 패턴에 미숙해서 확신이 없네요🥲 에단과 함께 얘기해보면 좋을 것 같아요!

2023-01-07 05:40 UTC, leeari95 commented on Fitfty/Projects/Coordinator/Sources/MainCoordinator.swift
> +        test.navigationItem.title = "주소를 변경해볼까요?"
이 부분은 에단이 조언주신대로 별도의 코디네이터를 만들어서 개선했습니다! 감사합니다~
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/10/commits/9dc7673406b6f87f0f13c6c5f75ecad060cbf995

2023-01-07 05:41 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +    @objc func viewPanned(_ panGestureRecognizer: UIPanGestureRecognizer) {
수정하였습니다. 감사합니당 😆
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/10/commits/e8d79c165cf32554293344a70ce445fa3b76f125

2023-01-07 05:41 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/ViewControllers/BottomSheetViewController.swift
> +        view.addGestureRecognizer(dimmedTap)
헉.. 제가 실수했네용,,,!! 발견해주셔서 감사해용 🥹
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/10/commits/e8d79c165cf32554293344a70ce445fa3b76f125

2023-01-07 06:12 UTC, dudtjs1021ej approved these changes
수정사항 확인했습니다~!! 고생하셨어요👍 바로 머지 하시면 될 것 같습니당ㅎㅎ

2023-01-07 06:12 UTC, merged