[Refactor] 메인피드, 주소설정, 날씨상세 화면 UI 피그마 수정사항 반영하여 개선
YAPP-Github/21st-iOS-Team-2-iOS pull request #20
Opened 2023-01-29 07:55 UTC by leeari95

### 📕 Issue

> 관련 이슈를 연결합니다.

fix x

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역, 변경 사항을 포함합니다.

- [x] 레이아웃 수정
	- 메인피드
	- 주소설정
	- 날씨상세

### 📘 작업 유형

- [ ] 신규 기능 추가
- [ ] 버그 수정
- [x] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

### 📱 테스트 방법

> PR 리뷰어가 변경사항을 확인할 수 있는 방법을 서술합니다. 의도하는 테스트 결과도 같이 서술하면 더 좋습니다.

- x

### 📝 리뷰 노트

> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있다면 PR 리뷰를 돕기 위해 서술합니다. 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트를 요청하는 경우에도 같이 작성해주면 좋습니다.

- 피그마 참고하여 UI 및 레이아웃, 스타일 등등을 수정하여 개선했습니다~

### 🏞️ 스크린샷

> 작업 내용과 관련된 화면을 추가합니다.

|![image](https://user-images.githubusercontent.com/75905803/215312698-5604d43e-21bc-4796-9519-c41d9569a552.png)|![image](https://user-images.githubusercontent.com/75905803/215312701-c9c92fc1-10fd-4b20-b157-11de1f0beb46.png)|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/75905803/215312820-6bcadf83-885d-43c1-be9f-05a07ae4f702.png)|-|

2023-01-29 08:04 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/Main/Views/Address/AddressCell.swift
> -
주소 설정 화면의 온도 Label을 제거했어용~

2023-01-29 08:05 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/Main/Views/Main/CodyCell.swift
> +
임시로 상태값을 구현해두었어요.
추후 따로 Cell의 ViewModel이 필요할 것 같죠?

2023-01-29 08:05 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/Main/Views/Main/WeatherCell.swift
> +        stackView.addArrangedSubviews(hourLabel, weatherIconImageView, tempLabel)
시간별 날씨 cell 내부 온도 label 추가했습니다~

2023-01-30 08:39 UTC, dudtjs1021ej requested changes
아리 고생하셨습니당 정말 빠르시네여..👍

<img src = "https://user-images.githubusercontent.com/77915491/215427188-03a08c83-74c5-4968-9e6a-54c0587bf945.png" width="30%">

추가로 아리가 캡쳐한곳에선 검색어를 입력해주세요 label이 안보이는데 제가 돌려볼땐 보이더라구요..?!
요 부분만 hidden 처리하면 될 것 같습니다..!!
나머진 완벽합니다✨

2023-01-30 08:39 UTC, dudtjs1021ej commented on Fitfty/Projects/Common/Resources/Images.xcassets/weather/rainOrSnow.imageset/Contents.json
> +}
[질문] 눈쪽 이미지가 살짝 깨져보여요😯 피그마상에서도 그런가여??

2023-01-30 08:39 UTC, dudtjs1021ej commented on Fitfty/Projects/Common/Resources/Images.xcassets/weather/snow.imageset/Contents.json
> +}
요기도 이미지 추출이 잘못 된 것 같아요..!

2023-01-30 08:41 UTC, leeari95 commented on Fitfty/Projects/Common/Resources/Images.xcassets/weather/rainOrSnow.imageset/Contents.json
> +}
오잉? 레슬리가 준 파일 그대로 받아서 넣은건데.... 다시 수정할게요!

2023-01-30 08:51 UTC, leeari95 commented
저 emptyLabel은 나중에 비즈니스 로직 들어가면 제대로 표시되도록 할거에요. 
지금은 임시방편으로 그냥 보이게 해두었어요! 😊

2023-01-30 08:53 UTC, leeari95 commented on Fitfty/Projects/Common/Resources/Images.xcassets/weather/snow.imageset/Contents.json
> +}
![image](https://user-images.githubusercontent.com/75905803/215430837-2936325a-893c-43c7-aad6-e9da911a7be7.png)

피그마에서 추출을 이런식으로 하니 제대로 추출이 되네용. 해결했습니다!!!

2023-01-30 09:23 UTC, dudtjs1021ej commented on Fitfty/Projects/Common/Resources/Images.xcassets/weather/snow.imageset/Contents.json
> +}
아하,,!! 역시 피그마 배운 아리..👍

2023-01-30 09:24 UTC, dudtjs1021ej approved these changes
아아 알겠습니당~~ 머지 하면 될 것 같아요👍

2023-01-30 11:39 UTC, merged