[Feature] 내 핏프티 수정 UI, 앨범 목록에서 사진 가져오기 구현
YAPP-Github/21st-iOS-Team-2-iOS pull request #29
Opened 2023-02-07 14:19 UTC by dudtjs1021ej

### 📕 Issue

>
### 📙 작업 내역

- [x] 기존에 `UploadCodyViewController` 네이밍을 `MyFitftyViewController` 로 변경
- [ ]  MyFitftyType(`modifyMyFitfty`, `uploadMyFitfty` )에 따라 내 핏프티 수정, 등록 VC 생성
- [ ] 내핏프티 등록, 수정 글자 제한 구현 (2200자)
- [ ] 앨범 목록 UI & 로직 구현

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] PR과 관련없는 변경사항이 없는가?
- [ ] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

### 📱 테스트 방법

### 📝 리뷰 노트

> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있다면 PR 리뷰를 돕기 위해 서술합니다. 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트를 요청하는 경우에도 같이 작성해주면 좋습니다.

- MVVM + Combine 처음 써봐서 이게 맞나..싶어요😂
- VC끼리 데이터 전달(선택한 사진, 선택한 앨범)은 `NotificationCenter` 사용해서 데이터 받은 쪽은 input, 보내는쪽은 output으로 구현했습니다...!
- 커스텀 앨범 구현하는게 생각보다 공수가 많이 드네요🥹 실제 디바이스에도 잘 되는지 테스트 해주시면 감사하겠습니당

### 🏞️ 스크린샷
<img src="https://user-images.githubusercontent.com/77915491/217269304-40ee969a-5d93-4b9c-819b-8a011ef0e554.png" width="30%"> <img src="https://user-images.githubusercontent.com/77915491/217269460-2794d274-a79d-49ac-b64d-28b022dd684e.png" width="30%"> <img src="https://user-images.githubusercontent.com/77915491/217269588-993279cd-9333-46b1-9226-e08a39df7b74.png" width="30%">

2023-02-07 14:32 UTC, dudtjs1021ej commented on Fitfty/Projects/Common/Sources/BarView.swift
> +                backgroundStackView.centerYAnchor.constraint(equalTo: centerYAnchor),
앨범쪽 BarView만 피그마 디자인이 수정되어서 
isChevronButtonHidden에 따라 레이아웃을 다르게 잡아주었습니다!

2023-02-07 14:32 UTC, dudtjs1021ej commented on Fitfty/Projects/Common/Sources/FitftyButton.swift
> +
버튼이 enable상태일때만 사진 등록을 해야해서 getStyle을 따로 만들었는데 괜찮나여...?

2023-02-07 14:32 UTC, dudtjs1021ej commented on Fitfty/Projects/Common/Sources/StyleTag.swift
> +    case luxury
스타일태그 추가했습니당!

2023-02-07 14:32 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +    }
텍스트 입력할 때 키보드에 textView가 가려져서 스크롤을 밑으로 내려주었어요!

2023-02-07 14:32 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/Album/AlbumListViewModel.swift
> +    }
선택한 앨범을 AlbumVC에 보내줘야해서 NotificationCenter로 보내줬습니다..!

2023-02-08 01:46 UTC, leeari95 requested changes
안녕하세요 썬~ 기능 구현하시느라 고생 많으셨습니다!!! 👏👏👏
앨범 너무 구현 잘해주신 것 같아요. 일단 시뮬레이터로 테스트 해봤는데, 문제 없는 것 같습니다.


## 저의 의견

> VC끼리 데이터 전달(선택한 사진, 선택한 앨범)은 NotificationCenter 사용해서 데이터 받은 쪽은 input, 보내는쪽은 output으로 구현했습니다...! (이런 상황에 input, output 맞게 구분한건지 궁금합니다)

아.. 이 부분 코드상에서는 뭔가 input 역할을 하는 메소드 같았는데, NotificationCenter 때문이였군요.
혹시 `delegate 패턴`은 고려해보시지 않으셨을까요?

코디네이터로 앨범목록을 띄워줄탠데, 그때 delegate도 같이 넘겨주어 구현해볼 수도 있을 것 같아요.
NotificationCenter은 아무래도 코드 흐름을 파악하기 어렵다고 해야할까요?
지금같이 코드양이 적을 때는 모르겠는데, 추후 유지보수할 코드 양이 많아진다면... 
코드 파악하는데 시간이 걸릴 것 같아서요. 한번 고민해보시고, 가능하다면 delegate 패턴으로 개선해보는 것도 좋을 것 같아요 ㅎㅎ

# 

자세한 사항은 코멘트로 남겨두었으니 확인 부탁드립니다.
혹시 의문이 가거나, 추가로 궁금하신 사항 있으면 언제든 코멘트나 디엠주시면 감사하겠습니다!!
고생 많으셨습니다~ 😊

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/Common/Sources/StyleTag.swift
> +    case luxury
오우! 저도 만드려고 했는데, 잘쓸께요 썬~ 🙏🏻

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/Coordinator/Sources/Main/AlbumListCoordinator.swift
> +    }
제가 앱을 실행해서 앨범 리스트를 X 버튼을 통해 닫으니까, 화면이 스르륵 내려가야할 것 같은데...
화면에서 갑자기 뿅!! 하고 사라지는 것 같아요. 
dismiss 메소드의 completion을 활용해보면 어떨까요?

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +        // 스마트 앨범 가져오기 (ex 즐겨찾는 항목)
네이밍으로 알아볼 수 있어서
여기 주석은 없어도 괜찮을 것 같아요. ☺️

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +            if smartAlbum.estimatedAssetCount == NSNotFound {
이 if문은 별도의 else가 없는 것 같은데, guard는 어떨까요?
그럼 코드 depth가 더 나아질 것 같아요!

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +                if smartAlbums.count > 0 {
이렇게 두번씩 체크하는 이유가 궁금합니다! 🙋🏻‍♀️

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +        }
이 부분이 위에 코드랑 반복되는 것 같아요. 메소드로 분리해볼 수 있을까요? 💪

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +            phAssets.append(asset)
이 경우엔 if문이 더 가독성이 좋아질 것 같은데, 어떻게 생각하시나요?

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +// 사진 접근 권한: 선택된 사진
이 부분도 제거해도 괜찮을 것 같아요 ㅎㅎ

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
>          (.warmWeather, false),
음.. 이 부분은 ViewModel이 가지고 있는 게 적절하지 않을까요?
뭔가 뷰에 보여줄 데이터 같다는 생각이 들어서요.
지금은 그런 로직이 안보이는 것 같은데, 추후 실제 게시물을 수정할 때도, 이 모델들을 초기화해주어야 할 수도 있구요.
그리고 뷰모델도 수정인지, 새등록인지 MyFitftyType을 가지고 있어야할 것 같아요.

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +    }
오... 너무 좋네요 👍👍👍

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +                    self?.applySnapshot(sections)
음.. 이미 sections라는 state값이 있는데, reload에도 sections를 추가해준 이유, 썬의 생각이 궁금하네요.
저라면 image를 바꾸는 이벤트, sections를 업데이트하는 이벤트 각각 보내볼 것 같다는 생각이 들어서요!

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/Album/AlbumListViewModel.swift
> +    func selectAlbum(index: Int)
Input에 있어야 할 메소드 같아요!

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/Album/AlbumViewModel.swift
> +    func selectImage(index: Int)
이 부분도요!

2023-02-08 01:46 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
> +}
output이 존재하지 않는데, 별도로 정의해주신 이유가 궁금하네요. 🤔

2023-02-08 01:51 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +    }()
음... 하나의 버튼으로 합치고,
사용자가 등록을 할 수 있는 상태인지, 아닌지를 판별해서 ViewModel에서 이벤트를 줄때마다
버튼의 스타일을 변경하는 건 어떤가요?

2023-02-08 01:52 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
음... 버튼의 상태를 바라보고 있는 방법보다는, ViewModel 단에서
사용자가 업로드를 할 수 있는 상태인지를 output으로 내보내주면 어떨까요?

2023-02-08 01:57 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +    }()
버튼 이름 때문이 오해했네요 ㅋㅋㅋ
등록, 수정 버튼 같은데, 네이밍을 다시한번 고민해보면 좋을 것 같아요!

2023-02-08 04:00 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +                if smartAlbums.count > 0 {
앗.. 중복코드네요..ㅎㅎㅎ 수정하겠습니다!

2023-02-08 04:08 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +    }()
enable, disable에 따라 표시해주는 버튼이 맞아요!
처음 VC가 로드될때 수정 화면은 rightBarButton이 활성화 되어있고 등록 화면은 비활성화 되어있어서 setNavigtaionBar()에서 그렇게 처리해주었습니다..!
등록화면에서 모든 태그를 선택하고 이미지랑 텍스트 입력이 되면 enable버튼으로 바꾸는 로직 추가할 예정입니당

2023-02-08 04:28 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +                    self?.applySnapshot(sections)
imge를 받아오고 다시 applySnapshot을 해줘야해서 섹션도 추가했는데
currentState.send를 sections 상태타입에도 보내면 되는군요..! 수정해보겠습니당

2023-02-08 04:44 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
> +}
나중에 코디 등록 구현할 때 output이 필요할 것 같아 미리 정의만 해두었는데.. 다시 생각해봐야 할 것 같네여ㅎ
output 코드 삭제하고 다시 올리겠습니당

2023-02-08 06:08 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
>          (.warmWeather, false),
tagItems들을 viewModel에서 가지고 있으면 
```swift
// MyFitftyViewController - setUpDataSource()

 case .weatherTag:
                    let cell = collectionView.dequeueReusableCell(WeatherTagCell.self, for: indexPath)
                    cell?.setUp(
                        weahterTag: self.weatherTagItems[indexPath.item].weatherTag,
                        isSelected: self.weatherTagItems[indexPath.item].isSelected
                    )
                    return cell ?? UICollectionViewCell()
```

요기 cell setUp 처리는 어떻게 해야 할까요?? ViewModelState를 하나 만들고 태그를 send해주면 될까여..?
게시물 수정할때 초기화는 해당 게시물의 선택 되었던 태그들 불러오는거 말하시는거 맞나용?

2023-02-08 06:57 UTC, dudtjs1021ej commented on Fitfty/Projects/Coordinator/Sources/Main/AlbumListCoordinator.swift
> +    }
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/37985d933682510378b7628dda9239eb4d650e32
메모리 누수 신경쓰다가 애니메이션 체크를 못했네여..😂 감사합니다 아리!!
```swift
func dismiss() {
        navigationController.dismiss(animated: true) {
            self.finishDelegate?.coordinatorDidFinish(childCoordinator: self)
        }
    }
```

이렇게 개선해보았어요!

2023-02-08 06:58 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +        // 스마트 앨범 가져오기 (ex 즐겨찾는 항목)
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/da4ed00402074a76f1beedafd768e82299d8cc49
주석 삭제했습니다!

2023-02-08 06:58 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +            if smartAlbum.estimatedAssetCount == NSNotFound {
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/da4ed00402074a76f1beedafd768e82299d8cc49
guard문으로 개선해봤어요!

2023-02-08 06:59 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +                if smartAlbums.count > 0 {
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/da4ed00402074a76f1beedafd768e82299d8cc49
수정완료!

2023-02-08 07:00 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +        }
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/da4ed00402074a76f1beedafd768e82299d8cc49
`smartAlbumsToAlbumInfos` 메소드 만들었습니당

2023-02-08 07:01 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +            phAssets.append(asset)
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/da4ed00402074a76f1beedafd768e82299d8cc49
else문에서 
`stopPointer.pointee = true` 를 처리해줬어요!

2023-02-08 07:01 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/PhotoService.swift
> +// 사진 접근 권한: 선택된 사진
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/259a2c5a238e4e2ccced78345aa101a97dc10acb
제거완료👍

2023-02-08 07:04 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +                    self?.applySnapshot(sections)
```swift
currentState.send(.reload(phAssetInfo.image))
currentState.send(.sections([
                MyFitftySection(sectionKind: .content, items: [UUID()]),
                MyFitftySection(sectionKind: .weatherTag, items: Array(0..<5).map { _ in UUID() }),
                MyFitftySection(sectionKind: .styleTag, items: Array(0..<7).map { _ in UUID() })
]))
```

이미지 선택했을 때 reload, sections 두 번 보내게 개선했어요
아 지금 보니 reload 네이밍이 좀 이상한 것 같은데 괜찮나요..?ㅋㅋㅋ

2023-02-08 07:05 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewModel/MyFitfty/MyFitftyViewModel.swift
> +}
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/8558f5875564239e134e6baade83b6e8a8fd51e8
지웠어요ㅎㅎ

2023-02-08 07:05 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
>          (.warmWeather, false),
넵 맞습니당.
어짜피 viewModel에서 sections를 send로 보낼 때마다, snapshot이 동작할탠데,
MyFitftyCellModel 타입을 별도로 구현해두고... 케이스별로 다른 타입을 가질 수 있도록 하면 어떨까요?

예를들어 태그라는 모델을 만들어서 name과, isSelected을 가지고 있고,
그 모델을 통해서 setUp 메소드 파라미터로 전달해주면 좋을 거 같아요.

예시는... MainFeed에 `MainCellModel.swift` 파일을 참고해주세요 !

2023-02-08 07:06 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +                    self?.applySnapshot(sections)
음... 코디사진은 어떤가용?

2023-02-08 07:07 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +                    self?.applySnapshot(sections)
오옹 codyImage로 수정해볼게요!

2023-02-08 07:12 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/90057bbdfcfe4bdee1a615c97b80925ce08800ba
`ViewModelState` 에 `completed(Bool)` 을 추가하고
input으로 `didTapUpload(isSelected: Bool)` 을 감지해서 사진이 선택되었을때만 dismiss되게 구현했는데.. 괜찮나요??

2023-02-08 07:20 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
제가 놓쳤던 부분이 있었네용...?
이제보니 selectedIndex도 ViewController가 아니라 ViewModel이 가지고 있는게 맞는 것 같습니다!!

2023-02-08 07:21 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
202번 줄에 selectedIndex를 할당해주고 있는데, 이걸 input으로 보내면 어떨까요?

2023-02-08 07:25 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
그리고...
state에 값이 들어왔을 때, viewModel.output으로 selectImage를 보내는 것도 약간 이상한 것 같네요....

왜 이상하냐면, View는 ViewModel에서 받아온 데이터를 화면에 표시하기만 해야하는데... 
추가 동작을 더 하는 느낌이에요.

제가 생각하는[?] MVVM 중 ViewController의 역할은
사용자에게 받은 이벤트를 뷰모델로 쏴주고, 뷰모델에게 받은 데이터를 표시해준다고 생각해요.
근데 현재 저기 로직은 뷰를 닫기(coordinator.dismiss)만 해야할 것 같은데, 뷰모델로 또 이벤트를 보내고 있네용.

이 부분은 다시한번 고민해보시면 좋을 것 같습니다!

completed에서는 코디네이터만 호출되는 것이 적절할 것 같아요.

2023-02-09 02:35 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
> +                    self?.applySnapshot(sections)
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/9e0f9ce59b8309770481d5a43958e31b65a345b5
수정했어용

2023-02-09 02:42 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/8db8487dbc37f52abcc8d5024fb5bbbcebdc41c1
AlbumViewModel에서 selectedIndex를 관리하도록 개선했어요!

<br>
<br>

https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/b5b1196a3d9165d1b225d5491efa3799bb20f101
>completed에서는 코디네이터만 호출되는 것이 적절할 것 같아요.
이 부분 고민해봤는데..ViewModelState에 sendImage를 추가해서

```swift
 case .completed(let completed):
          guard completed else {
              return
          }
          self?.coordinator.dismiss()
case .sendImage:
          self?.viewModel.output.selectImage()

```

이렇게 개선해봤는데 제가 맞게 이해했나요?🥲

2023-02-09 02:43 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/MyFitftyViewController.swift
>          (.warmWeather, false),
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/a08cd7accaf574d5d30711b718e6b2c58a549f59
tagItems 뷰모델에서 관리하게 개선해봤어용

2023-02-09 02:53 UTC, dudtjs1021ej reviewed
@leeari95 아리 이번에도 꼼꼼한 리뷰 감사합니다!! 
delegate 패턴은 시간 부족으로... 여유 생기면 리팩토링 해볼게요🥹
<br>

https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/ee0ba1e4b23a76221614816651e033739956d141

추가로 사진을 선택하면 텍스트가 사라지는 현상을 발견해서...
delegate 패턴 사용해서 입력한 text를 뷰모델에서 처리하게끔 구현해봤어용

2023-02-09 14:56 UTC, leeari95 commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
흠... 이 부분은 같이 음성으로 이야기 나눠보면 좋을 것 같습니당!! 글로 하려니까 한계가 있네요 ㅋㅋㅋ🥹

2023-02-09 15:39 UTC, dudtjs1021ej commented on Fitfty/Projects/MainFeed/Sources/MyFitfty/ViewControllers/AlbumViewController.swift
> +        coordinator.dismiss()
https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/29/commits/9beef418feed705e27a4a1187eb12f6ee624133d
sendImage state지우고 didTapUpload()에서 바로 이미지 보내게 개선했어요!!
감사합니다 아리👍

2023-02-09 15:59 UTC, leeari95 approved these changes

2023-02-09 16:01 UTC, merged