[Feature] 날씨 API 구현
YAPP-Github/21st-iOS-Team-2-iOS pull request #8
Opened 2022-12-18 07:42 UTC by Daltonicc

### 📕 Issue

X

### 📙 작업 내역

- [x] Weather API 작업
- [x] WeatherAPI 테스트 코드 작업 

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [x] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [x] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

### 📱 테스트 방법

- 응답 잘 오는지 확인만 해보면 될 것 같아요
- 테스트도 한 번 돌려보시구,,

### 📝 리뷰 노트

- API 호출 방식 등 개선시키고 싶은 부분 있으면 말씀해주세요 !
- APIKey는 [노션](https://www.notion.so/yapp-workspace/API-f5e60b8586a24cc38ea3fa31fa508838)에 있어요 !

### 🏞️ 스크린샷

X

2022-12-18 08:30 UTC, leeari95 requested changes
에단!! 테스트 코드까지 작성해주시느라 고생 많으셨습니다!!! 😁
간단하게 궁금한 점을 코멘트로 남겨드렸습니다.

추가로 궁금한게...
테스트 케이스가 성공에 대한건 있는데 실패에 대한 것은 없는데 어떤 이유일까요?

코멘트 확인하시고 답글 남겨주시면 빠르게 확인해보겠습니다! 
감사합니다~

2022-12-18 08:30 UTC, leeari95 commented on Fitfty/Projects/Core/Sources/WeatherAPI.swift
> +        case .fetchWeather(let parameter), .fetchPastWeather(let parameter), .fetchMiddleWeatherTemperature(let parameter), .fetchMiddleWeatherInfo(let parameter):
[P3] 이 부분 라인 초과로 내려쓰기 해주시면 보기 편할 것 같습니다!

2022-12-18 08:30 UTC, leeari95 commented on Fitfty/Projects/Core/Sources/WeatherAPI.swift
> +                    print("didFinishRequest URL [\(response.request?.url?.absoluteString ?? "")]")
[P5] 이 print문이 필요한 이유가 뭔가요???

2022-12-18 08:30 UTC, leeari95 commented on Fitfty/Projects/Core/Sources/WeatherAPI.swift
> +                    }
[P2] 디코딩이 실패할 경우의 에러처리도 필요하지 않을까요?

2022-12-18 08:30 UTC, leeari95 commented on Fitfty/Projects/Core/Tests/WeatherAPITest.swift
> +        ]
[P4] 혹시 파라미터를 넣는 부분은 하드코딩밖에 방법이 없는건가요?

2022-12-20 12:50 UTC, Daltonicc commented on Fitfty/Projects/Core/Sources/WeatherAPI.swift
> +        case .fetchWeather(let parameter), .fetchPastWeather(let parameter), .fetchMiddleWeatherTemperature(let parameter), .fetchMiddleWeatherInfo(let parameter):
넵넵 완완입니다~~ https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/8/commits/a579beecfe5d7b85f882d14d5221147521566c1b

2022-12-20 12:50 UTC, Daltonicc commented on Fitfty/Projects/Core/Sources/WeatherAPI.swift
> +                    print("didFinishRequest URL [\(response.request?.url?.absoluteString ?? "")]")
요건 불필요하게 혹은 실수로 API가 여러 번 중복 호출 되고 있을 때, 로그상에서 빠르게 인지하기 위해 넣어둿습니다~

2022-12-20 12:50 UTC, Daltonicc commented on Fitfty/Projects/Core/Sources/WeatherAPI.swift
> +                    }
요건 생각해보니 코어모듈에서 옵셔널 바인딩해서 값을 넘기는게 맞을까라는 생각이 들었어요. 해당 모델 사용처에서 바인딩하는게 맞을거 같아서 옵셔널을 넘겨주는 방향으로 수정했습니다~~ https://github.com/YAPP-Github/21st-iOS-Team-2-iOS/pull/8/commits/1452ec3b3b06e0f3bda4460bc2b7c5980a208534

2022-12-20 12:50 UTC, Daltonicc commented on Fitfty/Projects/Core/Tests/WeatherAPITest.swift
> +        ]
음 테스트코드 작성이라 굳이 값을 외부에서 줄 필요는 없다고 생각했는데 다른 방법을 의도하신게 있을까요??

2022-12-20 12:51 UTC, Daltonicc commented
아리 리뷰 감사해요!!! 답이 늦었네요😅

실패에 대한 케이스는 제가 정확히 이해를 못했는데 테스트가 실패했을 때의 테스트 케이스가 필요하다는 말씀이신걸까요??(만약 API 호출이 실패하게 된다면 현재 제가 작성해둔 테스트에서 실패가 뜰거에요!)

추가로 환경변수 파싱 테스트는 로컬에서 테스트플랜 사용하지 않는 방향으로 수정해뒀어요 로컬에서 테스트하실때는 APIKey.swift파일에 키 채워넣어두고 테스트 돌리시면 될 거 같습니다~

2022-12-20 13:07 UTC, leeari95 commented on Fitfty/Projects/Core/Tests/WeatherAPITest.swift
> +        ]
아!! 파라미터 key값들이 String인데, 이 부분이 하드코딩이라는 생각이 들어서 말씀드린거였어요!
나중에 테스트코드가 아니더라도 실제 네트워크 요청할 때도 파라미터를 모두 저렇게 딕셔너리로 만들어서 넣어주어야 하지 않나요?

```swift
// MARK: - WeatherAPI
...

private extension TargetType {
    func updateParameters(_ parameter: [String: Any]) -> [String: Any] {
        var parameter = parameter
        parameter.updateValue(APIKey.apiKey.removingPercentEncoding ?? "", forKey: "serviceKey")
        parameter.updateValue("json", forKey: "dataType")
        return parameter
    }
}
```

아마 이 메소드를 통해서 파라미터 값들을 넘기는 것 같은데 제가 이해한게 맞을까요?
맞다면 파라미터를 딕셔너리 타입이 아니라 따로 구조체로 만들어서 개선해볼 수 있지 않을까요?
예를 들어 PastWeatherRequest라는 타입을 만들고, 해당 속성을 딕셔너리로 반환해주는 메소드를 구현해두고...
네트워크 요청할 때는
```swift
let request = PastWeatherRequest(numOfRows: 10, pageNo: 1, ...)
let response = try await WeatherAPI.request(target: .fetchPastWeather(parameter: request.parameter()))
```
이런식으로 메소드 호출해서 사용할 수도 있을 것 같아서요!!
제 생각이 이렇다는 걸 말씀드리는거라서 강요는 절대 아닙니다!
에단 생각도 궁금해요!!

2022-12-20 13:11 UTC, leeari95 commented
넵 제가 말씀드린 부분은 예를들어 statusCode가 404가 나왔을 때, 즉 실패에 대한 테스트 코드는 없어서 이 부분을 여쭤본 것이였어요!
근데 제가 다시 생각해보니까 테스트 코드가 실제 API를 호출해서 동작하는 테스트라서 실패에 대한 테스트코드를 구현하려면
Moya를 Mocking해서 가짜 Response를 넣어 작업을 해야되네요 ㅎㅎ... 이 부분은 그냥 넘어가셔도 괜찮을 것 같습니다!!!! 🙏🏻

2022-12-20 13:13 UTC, leeari95 approved these changes

2022-12-20 13:19 UTC, Daltonicc commented on Fitfty/Projects/Core/Tests/WeatherAPITest.swift
> +        ]
아아 그 말씀이셨군요!😅 구조체로 개선하는거 넘 좋은 생각 같습니당 그러면 요거는 나중에 아리랑 썬이 각자 사용하시게될 API Request 구조체 만들어서 사용하시는게 좋을 것 같아요 !! 아무래도 제 임의대로 만들어 두기에는 나중에 사용하시게될 분들의 의도를 해칠 수 있으니,, @dudtjs1021ej

2022-12-20 13:26 UTC, merged